# Generated by Django 5.2 on 2026-07-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_category', to=settings.AUTH_USER_MODEL, verbose_name='Owner User')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='File Name')),
                ('label', models.JSONField(verbose_name='Label')),
                ('file', models.FileField(upload_to='archive/', verbose_name='File')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('file_format', models.CharField(blank=True, max_length=50, verbose_name='File Format')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_file_category', to='archive.category', verbose_name='Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner User')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=180)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Downloaded At')),
                ('action', models.CharField(choices=[('delete', 'delete'), ('download', 'download')], default='download', help_text='type field', max_length=40, verbose_name='Action')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs_user_id', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'File Download Log',
                'verbose_name_plural': 'File Download Logs',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='archive_cat_name_993250_idx'),
        ),
    ]
