# Generated by Django 5.0.2 on 2026-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='owner_user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='owner_user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='owner_user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='user_id',
            field=models.CharField(max_length=80),
        ),
    ]
