# Generated by Django 5.0.1 on 2026-07-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_alter_category_owner_user_alter_file_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="owner_user",
        ),
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="file",
            name="owner_user",
        ),
        migrations.RemoveField(
            model_name="filedownloadlog",
            name="owner_user",
        ),
    ]
